name:          Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://MosaicDigital.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
